name: gundeck
description: runs a rundeck job using gundeck
author: Benjamin Nørgaard
inputs:
  ca-cert: 
    description: MTLS ca cert
    required: true
  client-cert:
    description: MTLS client cert
    required: true
  client-key:
    description: MTLS client key
    required: true
  host:
    description: Rundeck host
    required: true
  job:
    description: Rundeck job
    required: true
  options:
    description: Rundeck job options eg `-stackname somestack`
    required: false
  project:
    description: Rundeck project
    required: true
  token:
    description: Rundeck access token
    required: true
  docker-image:
    description: dockerimage used to run rundeck
    default: 063399264027.dkr.ecr.eu-west-1.amazonaws.com/tradeshift-public/gundeck-action:1.0.0
runs:
  using: node16
  main: dist/index.js
